#########################################################################
##
## This file is part of the SAMRAI distribution.  For full copyright 
## information, see COPYRIGHT and COPYING.LESSER. 
##
## Copyright:     (c) 1997-2016 Lawrence Livermore National Security, LLC
## Description:   configuration makefile included by all SAMRAI makefiles 
##
#########################################################################



.SUFFIXES:
.SUFFIXES: .o .F .f .c .C .cc

#
# The sed src_file finds the X.C file in the list of prerequisites. One would
# think this would exist as a Makefile symbol but the "$<" symbol is only
# usable in suffix rules. The sed rule extracts the .C filename.  This ONLY
# works if the .C file is changed.  It will break if only the .I or .h files
# change.  Thus is can be used for an intial build but does not
# really work in a development environment.
#

.F.o:
	$(F77) $(FFLAGS) -c $< -o $@
.f.o:
	$(F77) $(FFLAGS) -c $< -o $@
.c.o:
	$(CC) $(CFLAGS) $(CPPFLAGS) -c $< -o $@
.C.o:
	$(CXX) $(CXXFLAGS) $(CPPFLAGS) -c $< -o $@
.cc.o:
	$(CXX) $(CXXFLAGS) $(CPPFLAGS) -c $< -o $@

SHELL         = /bin/sh

SAMRAI_TARGET=standard

INCLUDE_SAM   = $(SAMRAI)/source
LIB_SAM       = $(OBJECT)/lib
BIN_SAM       = $(OBJECT)/bin

LIB_SUFFIX=.a

#
# GNUMake script to reverse strings.  This is recursive.
#
reverse = $(if $(1),$(call reverse,$(wordlist 2,$(words $(1)),$(1)))) $(firstword $(1))

#
# List of packages to process. 
# 
# Packages available : appu algs solv geom mesh math pdat xfer hier tbox
SAMRAI_LIBRARIES:=appu algs solv geom mesh math pdat xfer hier tbox
SAMRAI_LIBRARIES_R:=$(call reverse,appu algs solv geom mesh math pdat xfer hier tbox)

LIBSAMRAI=$(addsuffix $(LIB_SUFFIX),$(addprefix $(LIB_SAM)/libSAMRAI_,$(SAMRAI_LIBRARIES)))

LIBSAMRAIDEPEND   = $(LIBSAMRAI)

M4	      =	m4
RM            = rm -fr
CP            = cp
TEE           = tee
XARGS	      = xargs -n 150

F77           = gfortran
FFLAGS        = -g  $(FFLAGS_EXTRA)

CC            = gcc
CFLAGS        = -g  $(CFLAGS_EXTRA)

CXX           =  g++ 
CXXFLAGS      =	-g -Wall -Wextra -Wconversion  $(CXXFLAGS_EXTRA)

CPPFLAGS_EXTRA= 
CPPFLAGS      =  -I. -I$(OBJECT)/include -I$(INCLUDE_SAM) -I/usr/include -I/usr/lib/x86_64-linux-gnu/hdf5/serial//include    -I/usr/lib/openmpi/include/openmpi/opal/mca/event/libevent2021/libevent -I/usr/lib/openmpi/include/openmpi/opal/mca/event/libevent2021/libevent/include -I/usr/lib/openmpi/include    $(CPPFLAGS_EXTRA)

AR	      = ar

RPATH	      = -Wl,-rpath 

ifdef RPATH
LDFLAGS       =  -L$(LIB_SAM) -Wl,-rpath $(LIB_SAM)  -L/usr/lib/x86_64-linux-gnu/hdf5/serial//lib -Wl,-rpath /usr/lib/x86_64-linux-gnu/hdf5/serial//lib -L/usr/lib/openmpi/lib -Wl,-rpath /usr/lib/openmpi/lib -L/usr/lib/gcc/x86_64-linux-gnu/5 -Wl,-rpath /usr/lib/gcc/x86_64-linux-gnu/5 -L/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu -Wl,-rpath /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib -Wl,-rpath /usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib -L/lib/x86_64-linux-gnu -Wl,-rpath /lib/x86_64-linux-gnu -L/lib/../lib -Wl,-rpath /lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -Wl,-rpath /usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/5/../../.. $(LDFLAGS_EXTRA)
else
LDFLAGS       =  -L$(LIB_SAM)  -L/usr/lib/x86_64-linux-gnu/hdf5/serial//lib -Wl,-rpath /usr/lib/x86_64-linux-gnu/hdf5/serial//lib -L/usr/lib/openmpi/lib -Wl,-rpath /usr/lib/openmpi/lib -L/usr/lib/gcc/x86_64-linux-gnu/5 -Wl,-rpath /usr/lib/gcc/x86_64-linux-gnu/5 -L/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu -Wl,-rpath /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib -Wl,-rpath /usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib -L/lib/x86_64-linux-gnu -Wl,-rpath /lib/x86_64-linux-gnu -L/lib/../lib -Wl,-rpath /lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -Wl,-rpath /usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/5/../../.. $(LDFLAGS_EXTRA)
endif
LDLIBS        = $(LDLIBS_EXTRA)    -lhdf5    -lmpi   -ldl -lm  -lgfortran -lm -lquadmath

CXXLD_FLAGS   = -L$(LIB_SAM)   -L/usr/lib/x86_64-linux-gnu/hdf5/serial//lib -Wl,-rpath /usr/lib/x86_64-linux-gnu/hdf5/serial//lib -L/usr/lib/openmpi/lib -Wl,-rpath /usr/lib/openmpi/lib -L/usr/lib/gcc/x86_64-linux-gnu/5 -Wl,-rpath /usr/lib/gcc/x86_64-linux-gnu/5 -L/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu -Wl,-rpath /usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu -L/usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib -Wl,-rpath /usr/lib/gcc/x86_64-linux-gnu/5/../../../../lib -L/lib/x86_64-linux-gnu -Wl,-rpath /lib/x86_64-linux-gnu -L/lib/../lib -Wl,-rpath /lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -Wl,-rpath /usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/5/../../.. $(LDFLAGS_EXTRA)
CXXLDLIBS     = $(LDLIBS_EXTRA)    -lhdf5    -lmpi   -ldl -lm  -lgfortran -lm -lquadmath

PDAT_FORTDIR  = $(INCLUDE_SAM)/SAMRAI/pdat/fortran
SAMRAI_M4_FLAGS = -DPDAT_FORTDIR=$(PDAT_FORTDIR)

# Should the special SAMRAI targets be included in the Makefile.config
DEVELOPER_MAKEFILE=no

######################################################################
# Rules used in all directories.
######################################################################

CLEAN_COMMON_LIB_FILES = @$(RM) *.o
CLEAN_COMMON_CHECK_FILES = @$(RM) *visit *.log* foo *core* *.TVD* *.valgrind
CLEAN_COMMON_TEST_FILES = @$(RM) *.o *.f

# Used to control which types are created.
# Default is double, integer, bool, float, complex, char
SAMRAI_LIBRARY_TARGETS=libdefault libdcomplex

######################################################################
# Rules for SAMRAI developer builds only.
# These may conflict with user Makefiles, leave them off by default.
######################################################################

ifeq (${DEVELOPER_MAKEFILE},yes)

Makefile: $(SAMRAI)/$(SUBDIR)/Makefile.in  $(OBJECT)/config.status
	cd $(OBJECT) && $(SHELL) ./config.status --file=$(SUBDIR)/$@

endif


#########################################################################
##
## This file is part of the SAMRAI distribution.  For full copyright 
## information, see COPYRIGHT and COPYING.LESSER. 
##
## Copyright:     (c) 1997-2016 Lawrence Livermore National Security, LLC
## Description:   part of configuration makefile added for installations 
##
#########################################################################

SAMRAI		= /home/chris/Dropbox/GR_AMR
OBJECT		= /home/chris/Dropbox/GR_AMR
